### PR TITLE
fix for mysql text data fields

### PR DESCRIPTION
**Pull request by fdm1**

### CODE REVIEW

**Comment by Blue-Dog-Archolite** [comment]
Got the tests to back it up?

**Comment by fdm1** [comment]
passing test added to pull request

**Comment by fdm1** [comment]
Ran into an issue where queries with long results were still too long. Got a better solution that would set by the config file. In my fix, it would do what it did before this pull request unless those settings were set. https://gist.github.com/fdm1/520c53731dc8c6f9c97e

@Blue-Dog-Archolite I don't work with PG databases, so I'm curious if you know if these changes will have a negative (or any) effect with PG dbs? I'll hold off on pushing this change until I speak with you, and will refine my test(s) in the meantime.

UPDATE:
Finished change with rspec: https://gist.github.com/fdm1/0b744e19abf6fecb7e15

**Comment by nvreynolds** [comment]
Dabble bros

**Comment by fdm1** [comment]
lol. Hope you all are well :)

**Comment by Blue-Dog-Archolite** [comment]
:+1:

**Comment by robertzk** [comment]
@Blue-Dog-Archolite What's up dawg!

**Pull request closed without merging**
